# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# ruff: noqa: UP042

"""The ``/report/run-process`` row model, generated from its field snapshot."""

from __future__ import annotations

from enum import Enum
from typing import ClassVar

from pydantic import BaseModel, ConfigDict


class RunProcessReportFields(str, Enum):
    """The raw field names ENA serves in a ``/report/run-process`` row."""

    ERROR_MESSAGE = "errorMessage"
    ID = "id"
    PROCESS_DATE = "processDate"
    PROCESS_STATUS = "processStatus"


class RunProcessReport(BaseModel):
    """A record from ``/report/run-process``."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    #: Normalised field name -> the raw keys that may carry it.
    ALIASES: ClassVar[dict[str, tuple[str, ...]]] = {
        "run_accession": ("runAccession", "runId", "id"),
        "process_status": ("processStatus", "process_status"),
        "process_date": ("processDate", "process_date"),
        "error_message": ("errorMessage", "error_message", "errorMessages"),
    }

    run_accession: str = ""
    process_status: str = ""
    process_date: str = ""
    error_message: str = ""
