# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# ruff: noqa: UP042

"""The ``/report/run-files`` row model, generated from its field snapshot."""

from __future__ import annotations

from enum import Enum
from typing import ClassVar

from pydantic import BaseModel, ConfigDict


class FileReportFields(str, Enum):
    """The raw field names ENA serves in a ``/report/run-files`` row."""

    CHECKSUM = "checksum"
    CHECKSUM_METHOD = "checksumMethod"
    FILE_NAME = "fileName"
    ID = "id"
    RUN_ACCESSION = "runAccession"


class FileReport(BaseModel):
    """A record from ``/report/run-files``."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    #: Normalised field name -> the raw keys that may carry it.
    ALIASES: ClassVar[dict[str, tuple[str, ...]]] = {
        "accession": (
            "accession",
            "studyAccession",
            "sampleAccession",
            "runAccession",
            "experimentAccession",
            "analysisAccession",
            "id",
        ),
        "run_accession": ("runAccession", "runId", "id"),
        "filename": ("filename", "fileName", "name"),
        "checksum": ("checksum", "md5"),
        "checksum_method": ("checksumMethod", "checksum_method"),
    }

    accession: str = ""
    run_accession: str = ""
    filename: str = ""
    checksum: str = ""
    checksum_method: str = ""
