# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# ruff: noqa: UP042

"""The ``/report/samples`` row model, generated from its field snapshot."""

from __future__ import annotations

from enum import Enum
from typing import ClassVar

from pydantic import BaseModel, ConfigDict


class SampleReportFields(str, Enum):
    """The raw field names ENA serves in a ``/report/samples`` row."""

    ALIAS = "alias"
    COMMON_NAME = "commonName"
    FIRST_CREATED = "firstCreated"
    FIRST_PUBLIC = "firstPublic"
    ID = "id"
    RELEASE_STATUS = "releaseStatus"
    SAMPLE_ACCESSION = "sampleAccession"
    SAMPLE_ALIAS = "sampleAlias"
    SAMPLE_TITLE = "sampleTitle"
    SCIENTIFIC_NAME = "scientificName"
    SECONDARY_ACCESSION = "secondaryAccession"
    SECONDARY_ID = "secondaryId"
    SUBMISSION_ACCOUNT_ID = "submissionAccountId"
    TAX_ID = "taxId"
    TITLE = "title"


class SampleReport(BaseModel):
    """A record from ``/report/samples``."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    #: Normalised field name -> the raw keys that may carry it.
    ALIASES: ClassVar[dict[str, tuple[str, ...]]] = {
        "alias": ("alias", "studyAlias", "sampleAlias", "runAlias", "experimentAlias", "analysisAlias"),
        "accession": (
            "accession",
            "studyAccession",
            "sampleAccession",
            "runAccession",
            "experimentAccession",
            "analysisAccession",
            "id",
        ),
        "secondary_accession": ("secondaryAccession", "secondaryId"),
        "status": ("releaseStatus", "status"),
        "title": ("title", "studyTitle", "sampleTitle", "experimentTitle", "analysisTitle"),
    }

    alias: str = ""
    accession: str = ""
    secondary_accession: str = ""
    status: str = "UNKNOWN"
    title: str = ""
