# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.

"""The Webin Submission API's own response models."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class SubmissionJob(BaseModel):
    """The queued submission ``POST /submit/queue`` answers with."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    submission_account_id: str = Field("", alias="submissionAccountId")
    submission_id: str = Field("", alias="submissionId")
