# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# ruff: noqa: UP042

"""The ``/report/analyses`` row model, generated from its field snapshot."""

from __future__ import annotations

from enum import Enum
from typing import ClassVar

from pydantic import BaseModel, ConfigDict


class AnalysisReportFields(str, Enum):
    """The raw field names ENA serves in a ``/report/analyses`` row."""

    ALIAS = "alias"
    ANALYSIS_ACCESSION = "analysisAccession"
    ANALYSIS_ALIAS = "analysisAlias"
    ANALYSIS_TITLE = "analysisTitle"
    ANALYSIS_TYPE = "analysisType"
    ANALYSIS_TYPE_DESCRIPTION = "analysisTypeDescription"
    FIRST_CREATED = "firstCreated"
    FIRST_PUBLIC = "firstPublic"
    ID = "id"
    PROJECT_ID = "projectId"
    RELEASE_STATUS = "releaseStatus"
    SAMPLE_ID = "sampleId"
    STUDY_ACCESSION = "studyAccession"
    STUDY_ID = "studyId"
    SUBMISSION_ACCOUNT_ID = "submissionAccountId"


class AnalysisReport(BaseModel):
    """A record from ``/report/analyses``."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    #: Normalised field name -> the raw keys that may carry it.
    ALIASES: ClassVar[dict[str, tuple[str, ...]]] = {
        "alias": ("alias", "studyAlias", "sampleAlias", "runAlias", "experimentAlias", "analysisAlias"),
        "accession": (
            "accession",
            "studyAccession",
            "sampleAccession",
            "runAccession",
            "experimentAccession",
            "analysisAccession",
            "id",
        ),
        "secondary_accession": ("secondaryAccession", "secondaryId"),
        "status": ("releaseStatus", "status"),
        "title": ("title", "studyTitle", "sampleTitle", "experimentTitle", "analysisTitle"),
        "study_accession": ("studyAccession", "studyId"),
    }

    alias: str = ""
    accession: str = ""
    secondary_accession: str = ""
    status: str = "UNKNOWN"
    title: str = ""
    study_accession: str = ""
