# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# ruff: noqa: UP042

"""The ``/report/runs`` row model, generated from its field snapshot."""

from __future__ import annotations

from enum import Enum
from typing import ClassVar

from pydantic import BaseModel, ConfigDict


class RunReportFields(str, Enum):
    """The raw field names ENA serves in a ``/report/runs`` row."""

    EXPERIMENT_ACCESSION = "experimentAccession"
    ID = "id"
    RELEASE_STATUS = "releaseStatus"
    RUN_ACCESSION = "runAccession"
    RUN_ALIAS = "runAlias"
    SAMPLE_ACCESSION = "sampleAccession"
    STUDY_ACCESSION = "studyAccession"


class RunReport(BaseModel):
    """A record from ``/report/runs``."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    #: Normalised field name -> the raw keys that may carry it.
    ALIASES: ClassVar[dict[str, tuple[str, ...]]] = {
        "alias": ("alias", "studyAlias", "sampleAlias", "runAlias", "experimentAlias", "analysisAlias"),
        "accession": (
            "accession",
            "studyAccession",
            "sampleAccession",
            "runAccession",
            "experimentAccession",
            "analysisAccession",
            "id",
        ),
        "secondary_accession": ("secondaryAccession", "secondaryId"),
        "status": ("releaseStatus", "status"),
        "experiment_accession": ("experimentAccession", "experimentId"),
        "study_accession": ("studyAccession", "studyId"),
        "sample_accession": ("sampleAccession", "sampleId"),
    }

    alias: str = ""
    accession: str = ""
    secondary_accession: str = ""
    status: str = "UNKNOWN"
    experiment_accession: str = ""
    study_accession: str = ""
    sample_accession: str = ""
