# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# ruff: noqa: UP042

"""Generated lookup tables and models — the handwritten proxies' vocabulary."""

from __future__ import annotations

from enum import Enum
from typing import Final

from pydantic import BaseModel

from .reports import (
    AnalysisReport,
    ExperimentReport,
    FileReport,
    RunProcessReport,
    RunReport,
    SampleReport,
    StudyReport,
)


class ReportEntity(str, Enum):
    """The Reports API entities this client lists."""

    PROJECTS = "projects"
    SAMPLES = "samples"
    RUNS = "runs"
    EXPERIMENTS = "experiments"
    ANALYSES = "analyses"
    RUN_PROCESS = "run-process"
    FILES = "files"


REPORT_MODELS: Final[dict[ReportEntity, type[BaseModel]]] = {
    ReportEntity.PROJECTS: StudyReport,
    ReportEntity.SAMPLES: SampleReport,
    ReportEntity.RUNS: RunReport,
    ReportEntity.EXPERIMENTS: ExperimentReport,
    ReportEntity.ANALYSES: AnalysisReport,
    ReportEntity.RUN_PROCESS: RunProcessReport,
    ReportEntity.FILES: FileReport,
}

#: Entities whose submitted XML the Reports API serves at ``/{entity}/xml/…``.
XML_ENTITIES: Final = ("projects", "samples", "runs", "experiments", "analyses")

#: Receipt child tags that may carry accession info.
RECEIPT_ENTITY_TAGS: Final = (
    "ANALYSIS",
    "EXPERIMENT",
    "RUN",
    "SAMPLE",
    "SAMPLEGROUP",
    "STUDY",
    "DAC",
    "POLICY",
    "DATASET",
    "PROJECT",
    "CHECKLIST",
    "SUBMISSION",
)

__all__ = [
    "AnalysisReport",
    "ExperimentReport",
    "FileReport",
    "RECEIPT_ENTITY_TAGS",
    "REPORT_MODELS",
    "ReportEntity",
    "RunProcessReport",
    "RunReport",
    "SampleReport",
    "StudyReport",
    "XML_ENTITIES",
]
