# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.

"""The ENA operations this client calls, as taken from ENA's own definitions."""

from __future__ import annotations

from typing import Final, NamedTuple


class Endpoint(NamedTuple):
    """One ENA operation: its method, path template and query parameters."""

    method: str
    path: str
    params: tuple[str, ...]


SUBMIT: Final = Endpoint("POST", "/submit", ())

SUBMIT_QUEUE: Final = Endpoint("POST", "/submit/queue", ())

SUBMIT_POLL: Final = Endpoint("GET", "/submit/poll/{submissionId}", ())

BROWSER_XML: Final = Endpoint("GET", "/xml/{accession}", ("download", "gzip", "includeLinks"))

REPORT_PROJECTS: Final = Endpoint("GET", "/projects", ("format", "max-results", "status"))

REPORT_SAMPLES: Final = Endpoint("GET", "/samples", ("format", "max-results", "status"))

REPORT_RUNS: Final = Endpoint("GET", "/runs", ("format", "max-results", "status"))

REPORT_EXPERIMENTS: Final = Endpoint("GET", "/experiments", ("format", "max-results", "status"))

REPORT_ANALYSES: Final = Endpoint("GET", "/analyses", ("analysis-type", "format", "max-results", "status"))

REPORT_RUN_PROCESS: Final = Endpoint("GET", "/run-process", ("format", "max-results", "process-status"))

REPORT_PROJECTS_XML: Final = Endpoint("GET", "/projects/xml/{ids}", ("max-results",))

REPORT_SAMPLES_XML: Final = Endpoint("GET", "/samples/xml/{ids}", ("max-results",))

REPORT_RUNS_XML: Final = Endpoint("GET", "/runs/xml/{ids}", ("max-results",))

REPORT_EXPERIMENTS_XML: Final = Endpoint("GET", "/experiments/xml/{ids}", ("max-results",))

REPORT_ANALYSES_XML: Final = Endpoint("GET", "/analyses/xml/{ids}", ("max-results",))


REPORT_LIST: Final[dict[str, Endpoint]] = {
    "projects": REPORT_PROJECTS,
    "samples": REPORT_SAMPLES,
    "runs": REPORT_RUNS,
    "experiments": REPORT_EXPERIMENTS,
    "analyses": REPORT_ANALYSES,
    "run-process": REPORT_RUN_PROCESS,
}


REPORT_XML: Final[dict[str, Endpoint]] = {
    "projects": REPORT_PROJECTS_XML,
    "samples": REPORT_SAMPLES_XML,
    "runs": REPORT_RUNS_XML,
    "experiments": REPORT_EXPERIMENTS_XML,
    "analyses": REPORT_ANALYSES_XML,
}
